from tkinter import*
from tkinter import ttk
root=Tk()
root.geometry("600x350")
root.title("Охранная система")
butForAccess=Button(root, text="Подтвердить", fg='red',width=25,height=2)
butForAccess.place(x=200,y=230)
entForAccess=Entry(root, width=45, show='*')
entForAccess.place (x=150,y=150)
labForAccess=Label(root,text="Введите пароль",width=25,height=5)
labForAccess.place(x=200,y=50)
def Access(event):
    root.destroy()
    Registr=Tk()
    Registr.geometry("600x350")
    Registr.title("Регистрация")
    butForRegistr=Button(Registr, text='Перейти к заказу', fg='blue', width=25,height=2)
    butForRegistr.place(x=200,y=230)
    entForRegistrSurname=Entry(Registr,width=45)
    entForRegistrSurname.place(x=250,y=30)
    entForRegistrName=Entry(Registr,width=45)
    entForRegistrName.place(x=250,y=60)
    entForRegistrEmail=Entry(Registr,width=45)
    entForRegistrEmail.place(x=250,y=90)
    entForRegistrTelN=Entry(Registr,width=45)
    entForRegistrTelN.place(x=250,y=120)
    entForRegistrAddress=Entry(Registr,width=45)
    entForRegistrAddress.place(x=250,y=150)
    entForRegistrDate=Entry(Registr,width=45)
    entForRegistrDate.place(x=250,y=180)
    labForRegistrSurname=Label(Registr, text="Фамилимя",width=25,)
    labForRegistrSurname.place(x=10,y=30)
    labForRegistrName=Label(Registr, text="Имя",width=25)
    labForRegistrName.place(x=10,y=60)
    labForRegistrEmail=Label(Registr, text="Адрес электронной почты",width=25,)
    labForRegistrEmail.place(x=10,y=90)
    labForRegistrTelN=Label(Registr, text="Номер телефона",width=25)
    labForRegistrTelN.place(x=10,y=120)
    labForRegistrAddress=Label(Registr, text="Номер телефона",width=25)
    labForRegistrAddress.place(x=10,y=150)
    labForRegistrDate=Label(Registr, text="Крайний срок",width=25)
    labForRegistrDate.place(x=10,y=180)
    def Regist(event):
        Registr.destroy()
        Order=Tk()
        Order.geometry("600x350")
        Order.title('Заказ')
        labForOrderPic=Label(Order, text='Изображение',width=25)
        labForOrderPic.place(x=10, y=270)
        labForOrderNModule=Label(Order, text="Число модулей",width=25)
        labForOrderNModule.place(x=10, y=30)
        labForOrderTModule=Label(Order, text="Тип модуля",width=25)
        labForOrderTModule.place(x=10,y=60)
        labForOrderDeep=Label(Order, text="Глубина",width=25)
        labForOrderDeep.place(x=10, y=90)
        labForOrderHeight=Label(Order, text="Высота",width=25)
        labForOrderHeight.place(x=10, y=120)
        labForOrderWidth=Label(Order, text="Ширина",width=25)
        labForOrderWidth.place(x=10, y=150)
        labForOrderLength=Label(Order, text="Длина",width=25)
        labForOrderLength.place(x=10, y=180)
        labForOrderCModule=Label(Order, text="Цвет",width=25)
        labForOrderCModule.place(x=10, y=210)
        labForOrderMModule=Label(Order, text="Материал",width=25)
        labForOrderMModule.place(x=10,y=240)
        butForOrder=Button(Order, text="Принять заказ", fg="black", width=25, heigh=2)
        butForOrder.place(x=200,y=300)
        comboNModule=ttk.Combobox(Order,width=25)
        comboNModule.place(x=250,y=30)
        comboNModule['values']=('1','2','3','4','5')
        comboNModule.current()
        comboTModule=ttk.Combobox(Order,width=25)
        comboTModule.place(x=250,y=60)
        comboTModule['values']=('1','2','3','4','5')
        comboTModule.current()
        entForDeep=Entry(Order,width=28)
        entForDeep.place(x=250,y=90)
        entForHeight=Entry(Order,width=28)
        entForHeight.place(x=250,y=120)
        entForWidth=Entry(Order,width=28)
        entForWidth.place(x=250,y=150)
        entForLength=Entry(Order,width=28)
        entForLength.place(x=250,y=180)
        comboCModule=ttk.Combobox(Order,width=25)
        comboCModule.place(x=250,y=210)
        comboCModule['values']=('Красный','Синий','3','4','5')
        comboCModule.current()
        comboMModule=ttk.Combobox(Order,width=25)
        comboMModule.place(x=250,y=240)
        comboMModule['values']=('1','2','3','4','5')
        comboMModule.current()
        
    butForRegistr.bind("<Button-1>",Regist)

butForAccess.bind("<Button-1>",Access)
root.mainloop()
